### ISSUE TITLE
[Bug] Map won't publish (maybe filesize is too large)

### ISSUE THREAD

**Issue by mjp92067** [1point21interactive/kepler.gl#3]
**Describe the bug**
Unable to publish map (url)

**To Reproduce**
1. Upload this file (I used csv but github doesn't allow csv upload)[
[FATAL ENCOUNTERS DOT ORG SPREADSHEET1.xlsx](https://github.com/1point21interactive/kepler.gl/files/4711981/FATAL.ENCOUNTERS.DOT.ORG.SPREADSHEET1.xlsx)

](url)
2. Try to publish map and it never actually publishes

**Comment by swordensen** [comment]
@mjp92067 

Okay I increased the file size limit (from 20mb to 50mb) so it should work now. I tested it myself with the data provided and this is what it spit out. 

https://www.1point21interactive.com/maps/ag/9l6z7j0nnw/mb-size-test/
