### ISSUE TITLE
[Bug] Remove Kepler's default google analytics script.

### ISSUE THREAD

**Issue by swordensen** [1point21interactive/kepler.gl#5]
![image](https://user-images.githubusercontent.com/21202515/83431290-f9b12680-a3eb-11ea-95ec-0bb9af55fe2a.png)

Basically do the above ^

**Comment by swordensen** [comment]
@mjp92067 We do need the mapbox access token in order for the map to render properly. Otherwise we will be unable to fetch the mapbox tiles. 

@robh71  can correct me if I'm wrong but, generally these public facing tokens are considered safe because they are easy to obtain and only grant the user access to the tiles. There are API limits of course but, they are mindboggingly large and we can change the API token at anytime.

**Comment by robh71** [comment]
> @mjp92067 We do need the mapbox access token in order for the map to render properly. Otherwise we will be unable to fetch the mapbox tiles.
> 
> @robh71 can correct me if I'm wrong but, generally these public facing tokens are considered safe because they are easy to obtain and only grant the user access to the tiles. There are API limits of course but, they are mindboggingly large and we can change the API token at anytime.

Michael, I believe that's the case. Mapbox can compare the key with the referring URL and figure out any shenanigans if there's a mechanism to inform them what sites/domains the key should be allowed from.

from 
https://docs.mapbox.com/help/how-mapbox-works/access-tokens/

"Every token has a metadata object that contains properties with information about the token, like id (unique identifier) ,note (human readable name),scopes (capabilities), allowedURLs (URLs that token is authorized for), and timestamps for created and modified (last modification). "

The significant component here being the allowedURLs.

I would make sure that's not wide open or things could get weird.

**Comment by robh71** [comment]
oh and this little tidbit, from the same URL

"You can make your access tokens for web maps more secure by adding URL restrictions. When you add a URL restriction to a token, that token will only work for requests that originate from the URLs you specify. Tokens without restrictions will work for requests originating from any URL."

So yeah, thurr it is....

**Comment by swordensen** [comment]
GA script is removed closing this issue

Thanks @robh71 !
