### ISSUE TITLE
[Feature Request]: Ability to save maps so users can edit those same maps

### ISSUE THREAD

**Issue by mjp92067** [1point21interactive/kepler.gl#7]
**Is your feature request related to a problem? Please describe.**
There are times I want to edit a map that I've made. So we need ability to edit maps.

**Describe the solution you'd like**
Create ability to save maps. This also means we will need a table to view all produced maps with ability to edit, duplicate, delete maps.

**Comment by swordensen** [comment]
@mjp92067 moving this to the sftp service as well
