### ISSUE TITLE
[Feature Request]: Create table of URLs of all maps

### ISSUE THREAD

**Issue by mjp92067** [1point21interactive/kepler.gl#8]
**Is your feature request related to a problem? Please describe.**
We need to see all maps that have been created. So we can easily see everything that has been created. 

**Describe the solution you'd like**
Create a table of all maps that have been made.
- Map url
- Created by (we don't have users yet but we will need this eventually)
- Edit
- Delete
- View

**Comment by swordensen** [comment]
@mjp92067 I'm going to make this application universal to all map tools so I'm going to move it to the sftp service
