### ISSUE TITLE
[Bug] Text goes out of tooltip popup

### ISSUE THREAD

**Issue by mjp92067** [1point21interactive/kepler.gl#9]
**Describe the bug**

When you hover on some items in some maps like this one https://www.1point21interactive.com/maps/ag/2lvqghfadz/Black-People-Killed-by-Police-2000-2020/ the text sometimes goes out of the tooltips when you hover over dots, like in the example attached image.

**To Reproduce**
Hover over the blue dot in Oregon for example and you will see what I mean.

**Expected behavior**
Text should remain inside the popup window.

**Screenshots**

![image](https://user-images.githubusercontent.com/5207436/84101232-500cff00-a9c2-11ea-972b-077f9fb2873a.png)

**Desktop (please complete the following information):**
 - OS:  macOS
 - Browser Chrome
 - Version 83.0.4103.61

**Comment by swordensen** [comment]
this is easy i'll do this today

**Comment by swordensen** [comment]
this is resolved on live 

![image](https://user-images.githubusercontent.com/21202515/84182900-fe0abe80-aa3f-11ea-9b96-42ef946b89b1.png)
